AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quote Lambda Application.
Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      AllowMethods: "'GET, POST, PATCH, OPTIONS'"

Resources:
  QuoteLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./  # local path to Lambda function code
      Handler: ebulter.quote.lambda.QuoteHandler::handleRequest
      Runtime: java17
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource:
                Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Quotes
      Events: # The Events property enables AWS SAM to create an API Gateway
        GetQuote:
          Type: Api
          Properties:
            Path: /quote
            Method: get
        PostQuote:
          Type: Api
          Properties:
            Path: /quote
            Method: post
        PatchLike:
          Type: Api
          Properties:
            Path: /quote/{id}/like
            Method: patch
        GetLiked:
          Type: Api
          Properties:
            Path: /quote/liked
            Method: get

